# WELOCOME TO NUMPY 

In [1]:
import numpy as np


In [2]:
myarr = np.array([[3,4,53,3,6,5]], np.int8)


In [3]:
myarr[0,1]

4

In [4]:
myarr.shape

(1, 6)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] = 45


In [7]:
myarr

array([[ 3, 45, 53,  3,  6,  5]], dtype=int8)

## Array creation: Conversion from other Python structures

In [8]:
listarray = np.array([[1,3,4],[3,4,6],[3,2,3]])

In [9]:
listarray

array([[1, 3, 4],
       [3, 4, 6],
       [3, 2, 3]])

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.size 

9

In [12]:
np.array({34,23})

array({34, 23}, dtype=object)

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,4,4)

In [18]:
lspace

array([1., 2., 3., 4.])

In [19]:
emp = np.empty((4,6))

In [20]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([1., 2., 3., 4.])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr = arr.reshape(3,33)

In [29]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
x = [[1,3,4],[3,4,6],[3,2,3]]

In [32]:
ar = np.array(x)

In [33]:
ar

array([[1, 3, 4],
       [3, 4, 6],
       [3, 2, 3]])

In [34]:
ar.sum(axis=0)

array([ 7,  9, 13])

In [35]:
ar.sum(axis=1)

array([ 8, 13,  8])

##Transpose array

In [36]:
ar.T

array([[1, 3, 3],
       [3, 4, 2],
       [4, 6, 3]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
3
4
3
4
6
3
2
3


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [41]:
ar.nbytes

36

In [42]:
one = np.array([1,3,4,625])

In [43]:
one.argmax()

3

In [44]:
one.argmin()

0

In [45]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [46]:
ar

array([[1, 3, 4],
       [3, 4, 6],
       [3, 2, 3]])

In [47]:
ar.argmin()

0

In [48]:
ar.argmax()

5

In [49]:
ar.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [50]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [51]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [52]:
import sys

In [53]:
py_ar = [0,4,55,2]

In [54]:
np_ar = np.array(py_ar)

In [55]:
sys.getsizeof(1) * len(py_ar)

112